#!/usr/bin/zsh

# fv function opens text files in nvim. Fzf displays a preview window.
vz (){
    nvim $(fd -HI --type f  --exclude='.cache' --exclude='.atom' --exclude=aur \
        --exclude=chromium --exclude='.git' --color=always . $@ | fzf -m --ansi \
        --preview 'bat --color=always {}')
}

# fg function  opens graphic files (jpg, png and arw) files in gimp.
gz (){
    gimp $(fd -I --type f --exclude=aur --color=always 'png$|jpg$|arw$' $@ | fzf -m --ansi)
}

cz (){
    $(fd -IH --type d  --exclude='/run' --exclude='/windata'  --exclude='/media'\
       --exclude='/mnt' --color=always . / |fzf -e --ansi)
}
