#!/usr/bin/zsh

PS1='%B%F{51}[%n:%2~]%#%b%f '		# Default prompt without any changes in git repository.

if [[ -d .git ]]; then
    BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
    
    if [[ $(git status -s) =~ '^ M' ]]; then				# File(s) modified (yellow).
        MODIFIED=true
    else
        unset MODIFIED
    fi
    
    if [[ $(git status -s | grep -v '^ M') =~ '^A' ]]; then	# New file added to staging area (green).
        ADDED=true
    else
        ADDED=""
	unset ADDED
    fi
    
    if [[ $(git status -s) =~ '^M' ]]; then				# Modified files in staging area (magenta).
        STAGED=true
    else
        unset STAGED
    fi

    if [ $MODIFIED ]; then    
	PS1="%B%F{226}(${BRANCH})%F{51}[%n:%2~]%#%b%f "			# Yellow prompt.
    fi

    if [ $ADDED ]; then
        PS1="%B%F{46}(${BRANCH})%F{51}[%n:%2~]%#%b%f "			# Green prompt.
    fi

    if [[ $MODIFIED && $ADDED ]]; then
        PS1="%B%F{201}(${BRANCH})%F{51}[%n:%2~]%#%b%f "			# Magenta prompt.
    fi

    # This line below to be uncommented for debugging purposes.
    #printf "MODIFIED = %s ADDED = STAGED = %s\n" $MODIFIED $ADDED $STAGED
fi
