#!/usr/bin/zsh

PS1='%B%F{51}[%n:%2~]%#%b%f '		# Default prompt without any changes in git repository.

if [[ -d .git ]]; then
    BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
    
    if [[ $(git status -s) =~ '^ M' ]]; then		# File(s) modified (yellow).
        PS1="%B%F{226}(${BRANCH})%F{51}[%n:%2~]%#%b%f "
        MODIFIED=true
    else
        unset MODIFIED
    fi
    
    if [[ $(git status -s) =~ '^A' ]]; then			# New file added to staging area (magenta).
        PS1="%B%F{201}(${BRANCH})%F{51}[%n:%2~]%#%b%f "
        ADDED=true
    else
        unset ADDED
    fi
    
    if [[ $(git status -s) =~ '^M' ]]; then
        PS1="%B%F{46}(${BRANCH})%F{51}[%n:%2~]%#%b%f "	# Modified files in staging area (green).
        STAGED=true
    else
        unset STAGED
    fi
fi
