language: ruby
cache: bundler
sudo: false
dist: trusty

branches:
  only: master

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

before_install:
  - eval "$(curl --connect-timeout 30 --retry 3 -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
  - gem update --system --conservative || (gem install "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem install --remote bundler || gem install --remote bundler -v "1.17.3"
  - gem install --user-install executable-hooks
  - bundle --version

env: NVIM_RUBY_LOG_LEVEL=DEBUG NVIM_RUBY_LOG_FILE=ci.log
script: bundle exec rake --trace
